spring:
  application:
    name: fidelicrmbackend

  # Configuración de Base de Datos
  datasource:
    url: jdbc:postgresql://localhost:5435/fidelicrm_dev
    username: dev_admin
    password: dev_password
    driver-class-name: org.postgresql.Driver

  # Configuration flyway
  flyway:
    enabled: true
    baseline-on-migrate: true
    connect-retries: 10

  # Configuración de JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Configuración de RabbitMQ
  rabbitmq:
    host: localhost
    port: 5675
    username: user_v1
    password: pass_v1

  # Desactivamos el soporte automático de Docker Compose de Spring Boot
  # para evitar conflictos, ya que tú lo manejas manualmente.
  docker:
    compose:
      enabled: false

# Configuración de AWS LocalStack
aws:
  s3:
    endpoint: http://localhost:4569
    region: us-east-1
    access-key: test
    secret-key: test
    bucket-name: fidelicrm-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics